### ISSUE TITLE
Duplicate lists on the main repo page after navigating away and back

### ISSUE THREAD

**Issue by xt0rted** [npmhub/npmhub#102]
While testing #100 I noticed that if you load https://github.com/npmhub/npmhub, then navigate to https://github.com/npmhub/npmhub/blob/master/package.json, then use the back button to return to the main page the list of dependencies shows twice. Do it again and it'll show three times etc. I'm not seeing this behavior on the `package.json` page, only on the main repo page with the readme.

This is happening in both Chrome and FireFox on Windows 10.

**Comment by fregante** [comment]
Are you sure it doesn’t just happen in your PR? We have a check for that 

https://github.com/npmhub/npmhub/blob/1612065210afcec8df80064567b736f507335dfc/source/content.js#L184

**Comment by xt0rted** [comment]
That's the issue, I adjusted the header and now `npmhub-header` is only emitted on GitLab which is why this started happening.
