### ISSUE TITLE
It doesn't work if GitHub defers loading of the file list

### ISSUE THREAD

**Issue by fregante** [npmhub/npmhub#107]
If GitHub decides to load the file list asynchronously, npmhub won't see the file and won't appear.

This happens on:

- any repo, sometimes, e.g. https://github.com/fregante/object-fit-images
- when seeing non-default branches, e.g. https://github.com/npmhub/npmhub/tree/svelte

Similar problem: #106

Solution: use select + MutationObserver to detect a deferred load and wait for it
https://github.com/sindresorhus/refined-github/blob/master/source/github-events/on-file-list-update.ts

**Comment by notlmn** [comment]
Doesn't `element-ready` help in this regard?

**Comment by fregante** [comment]
I'd rather not use `element-ready` for deferred elements because it's not safe (if the DOM changes, `element-ready` will continue querying the DOM 60 times per second, forever)

**Comment by maxloh** [comment]
@fregante How about the [Intersection Observer API
](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)?

**Comment by fregante** [comment]
You can't observe something that isn't on the page. You need MutationObserver for that, as suggested
