### ISSUE TITLE
The Chrome Store deployment is failing

### ISSUE THREAD

**Issue by fregante** [npmhub/npmhub#108]
Probably the key has expired or is invalid

**Comment by zeke** [comment]
Do you need my help on this @fregante?

**Comment by fregante** [comment]
No, I just haven't had the time to follow the token instructions. My client ID is [hardcoded](https://github.com/npmhub/npmhub/blob/147154deca1e5d40c272848ba4422a100e474b7d/.github/workflows/deployment.yml#L55) so I'll have to do it

**Comment by zeke** [comment]
Ok sounds good. Thanks for maintaining this project all these years!

**Comment by fregante** [comment]
Fixed!

Last run: https://github.com/npmhub/npmhub/actions/runs/243876983
