### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by fregante** [npmhub/npmhub#112]
It'd be great to publish this for Safari now that it supports same API.

Related threads: 
- https://github.com/sindresorhus/refined-github/issues/14
- https://github.com/notlmn/browser-extension-template/issues/31

@zeke do you have an Apple developer account?

**Comment by zeke** [comment]
Alas, I just left my apple developer program membership die, because I haven't been building any Electron apps lately. 😬 

I'd be happy to chip in to help pay for one though...

**Comment by fregante** [comment]
> do you have an Apple developer account?

I got one now thanks to Sindre 😁

The extension has already been accepted by the App Store 🍰 and will be public soon but I plan to polish a few things before advertising it. Ideally we'd also update the really-out-of-date website too.
