### ISSUE TITLE
Latest release in CWS (published today) is 2020.11.20 instead of 2020.12.19

### ISSUE THREAD

**Issue by darkred** [npmhub/npmhub#122]
I've noticed that the npmhub version published in [CWS](https://chrome.google.com/webstore/detail/npmhub/kbbbjimdjbjclaebffknlabpogocablj) today is 2020.11.20 .
Today release in GitHub is [2020.12.19](https://github.com/npmhub/npmhub/releases/tag/2020.12.19) .
If it helps, seeing the [2020.11.20...2020.12.19 changelog](https://github.com/npmhub/npmhub/compare/2020.11.20...2020.12.19), all the commits are meta, except this one: https://github.com/npmhub/npmhub/commit/3c058e8ec0d2742268fb40b805f0c3e725ec9a46

Also, the latest 'Release' action run has failed for Chrome: https://github.com/npmhub/npmhub/actions/runs/432029150 : 
> Error Code: ITEM_NOT_UPDATABLE
> Details: The item cannot be updated now because it is in pending review, ready to publish, or deleted status.

**Comment by fregante** [comment]
Thanks, I updated the chrome store listing (screenshots etc) and published that, *then* I tried to release a new version from the repo but that one was still happening. I’ll upload it manually, probably

**Comment by fregante** [comment]
Done. Waiting review

**Comment by darkred** [comment]
It's published now. Thank you.
