### ISSUE TITLE
The dependency list is hard to reach

### ISSUE THREAD

**Issue by fregante** [npmhub/npmhub#125]
Reaching npmhub means _Scrolling all the way down, but not quite all the way._

I think it makes sense to somehow block the scroll once the user reaches the bottom, and _only then_ allow scrolling further.

This is generally achieved by only hiding the whole table once the bottom is reached. However maybe it should already generate it _before_ then, so that it will be ready.

**Comment by fregante** [comment]
Or maybe we should just add a button to scroll to npmhub somewhere near the top, maybe in the sidebar. This is probably faster for the user, easier to manage, except that it's an extra UI element.

**Comment by fregante** [comment]
> add a button to scroll to npmhub

<img width="249" alt="Screen Shot 11" src="https://user-images.githubusercontent.com/1402241/111383690-2d54f880-866e-11eb-96c5-5b1caa01f8f2.png">

This might be a good position, at least on the repo home

**Comment by Nisgrak** [comment]
This issue are open to a new PR?
