### ISSUE TITLE
Easy way to migrate npmhub to TypeScript

### ISSUE THREAD

**Issue by dhysuiej** [npmhub/npmhub#127]
Since Parcel supports TS out of the box I thought changing the file extensions with JS code from `.js` to `.ts` and the JS tags in the `.svelte` files from `<script>` to `<script lang="ts">` would do the trick, but I get the error `Segmentation fault: 11` without showing any more details when running `npm run build`.

Has anyone tried to migrate the npmhub to TS or enable TS on some other Parcel+Svelte project successfully.

**Comment by dhysuiej** [comment]
I'm closing this because after removing `package-lock.json`  and installing all packages the build command completed successfully.

**Comment by fregante** [comment]
I don’t know why you’re opening this kind of issue here because I’m not interested in using TypeScript in this project
