### ISSUE TITLE
"Dependencies" title not in format with "readme.md" title

### ISSUE THREAD

**Issue by ritikbheda** [npmhub/npmhub#143]
As the issue title says, the title of "readme.md" and "dependencies" are not in the same format and also the title heading also do not have the proper height than that of "readme". See screenshots below for a better idea:

This is the current npmhub version shows "Dependencies"
> ![DependenciesOriginal](https://user-images.githubusercontent.com/60680215/136863185-7965e155-7efd-4a40-be94-358d671bebce.JPG)

This is how readme is made
> ![readme](https://user-images.githubusercontent.com/60680215/136863284-461beea8-2ee5-4a43-a370-bf8ce670ea94.JPG)

Let us try to create our added titles just like readme.

**Comment by fregante** [comment]
Yeah it would be nice to update the style/classes to match it. It was attempted before but it ended up not being merged.
