### ISSUE TITLE
The dropdown is covered by `peerDependencies` table

### ISSUE THREAD

**Issue by charkour** [npmhub/npmhub#149]
Thank you for this awesome extension (and your other extensions).

I've been using npmhub for a while and noticed the dropdown is hidden when the project has peer dependencies. This can be seen in [this repo](https://github.com/charkour/zundo) that has peer dependencies. 

![image](https://user-images.githubusercontent.com/33156025/143788602-2ff1e33d-aff4-4e45-871f-43587ec1ac79.png)

Thanks for taking a look at this!

**Comment by charkour** [comment]
I would be willing to make a PR.

**Comment by fregante** [comment]
This was fixed in #148 but I forgot to release it 😅

**Comment by charkour** [comment]
Thanks for the quick response!
