### ISSUE TITLE
Submission in CWS failed due to `HTTPError: Response code 400 (Bad Request)`

### ISSUE THREAD

**Issue by darkred** [npmhub/npmhub#153]
I noticed that the latest release, 2022.3.17, is still not available in [CWS](https://chrome.google.com/webstore/detail/npmhub/kbbbjimdjbjclaebffknlabpogocablj) 18 days now, so I checked the relevant Release action and found that has failed for Chrome: https://github.com/npmhub/npmhub/runs/5580740222?check_suite_focus=true

Here is the error message:

```
- Publishing
Error
HTTPError: Response code 400 (Bad Request)
   at Request.<anonymous> (/home/runner/.npm/_npx/f7427b1617d822ea/node_modules/got/dist/source/as-promise/index.js:117:42)
   at processTicksAndRejections (node:internal/process/task_queues:96:5) {
 code: 'ERR_NON_2XX_3XX_RESPONSE',
(...)
Error: Process completed with exit code 1.
```

**Comment by fregante** [comment]
Thank you. It's failing because the publisher email is not verified.

@zeke can you verify the email? The URL should be https://chrome.google.com/webstore/devconsole/a5606c17-ae3b-42a0-8f18-6030f33bbbc1/settings

If not, open https://chrome.google.com/webstore/devconsole/ and find this view

<img width="893" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/161473668-75b6e35b-339c-4aaa-afb6-71c02774edf4.png">

**Comment by fregante** [comment]
You'll have you follow the link here I suggested here, not the email

**Comment by zeke** [comment]
Oh sorry, I misread. Email confirmed 👍🏼 

<img width="373" alt="Screen Shot 2022-04-04 at 10 28 46 PM" src="https://user-images.githubusercontent.com/2289/161684999-9ff147f3-ea4d-4cf6-8757-d773d04d986e.png">

**Comment by fregante** [comment]
Pending review now

<img width="1055" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/161809466-fbb4dbd6-bbfc-4a73-bffd-77432e641f73.png">

**Comment by zeke** [comment]
<img width="608" alt="Screen Shot 2022-04-11 at 11 01 07 AM" src="https://user-images.githubusercontent.com/2289/162801252-f967d99b-8e59-4d84-a395-667f778fb474.png">

**Comment by fregante** [comment]
#154

**Comment by fregante** [comment]
<img width="222" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/163108757-f1ea3570-b8fb-44c2-bea9-45ea443586e4.png">
