### ISSUE TITLE
Make the list of dependencies the same width as the readme

### ISSUE THREAD

**Issue by azat-io** [npmhub/npmhub#172]
<img width="2041" alt="image" src="https://github.com/npmhub/npmhub/assets/5698350/729d2bab-8b21-427d-84d4-24637995051d">

I suggest making the list of dependencies the same width as the readme. The current implementation looks a bit strange visually.

**Comment by fregante** [comment]
Thank you for the suggestion. See https://github.com/npmhub/npmhub/pull/140#issuecomment-940805192
