### ISSUE TITLE
Unrendered markdown in some package description

### ISSUE THREAD

**Issue by jerone** [npmhub/npmhub#174]
1. https://github.com/sindresorhus/dot-prop#dependencies
2. Dev Dependencies
3. `expect-type` ➡ `[![CI](https://github.com/mmkal/expect-type/actions/workflows/ci.yml/badge.svg)](https://github.com/mmkal/expect-type/actions/workflows/ci.yml) [![](https://byob.yarr.is/mmkal/expect-type/coverage)](https://github.com/mmkal/expect-type/actions/workflows/c`

![image](https://github.com/npmhub/npmhub/assets/55841/8338ecb9-2db8-48b0-b1dd-bba6bdc6b3c0)

**Comment by fregante** [comment]
That’s because they don’t set a description, so npm uses the whole readme file: https://github.com/mmkal/expect-type/blob/main/package.json

Npmjs.com shows the same content in lists:

https://www.npmjs.com/search?q=%20expect-type

**Comment by fregante** [comment]
Maybe I can detect and discard descriptions that start with `![` or `[![`, as that is very likely followed by useless markdown

**Comment by fregante** [comment]
Done. If you find any more examples that don't start with `[!` or `![` let me know
