### ISSUE TITLE
Doesn't render in new repository overview

### ISSUE THREAD

**Issue by texastoland** [npmhub/npmhub#175]
`New repository overview` used to be in feature preview but recently became default.

**Comment by fregante** [comment]
Thank you for the report. Feels like they've been breaking npmhub every few months now 😩

**Comment by texastoland** [comment]
I'm glad you maintain it! I'm tracking zvizvi/GitHub-Web-IDE#39 and hediet/browser-ext-github-monaco#55 for the same reason. It's a testament to the usefulness of your extension that I immediately missed it 🙌🏼
