### ISSUE TITLE
Autodeployment automation

### ISSUE THREAD

**Issue by bfred-it** [npmhub/npmhub#19]
Currently the deployment steps are:

0. Update the version in `extension/manifest.json`
0. Create a commit for it
0. Create a tag with the same version

If you're ok with it, I can skip the first two steps by dynamically update the version during deployment (without committing it)

You can see it in action on my GitHub Clean Feed:
- [.travis.yml](https://github.com/bfred-it/github-clean-feed/blob/648f8fe870e49053b4aeae1180285a1d6945853c/.travis.yml#L9)
- [package.json](https://github.com/bfred-it/github-clean-feed/blob/648f8fe870e49053b4aeae1180285a1d6945853c/package.json#L24-L26)
- [manifest.json](https://github.com/bfred-it/github-clean-feed/blob/648f8fe870e49053b4aeae1180285a1d6945853c/extension/manifest.json#L5)

**Comment by zeke** [comment]
Can you distill this into an npm-script one-liner somehow?

**Comment by bfred-it** [comment]
Yes, sorry, the demo links are currently down. The oneliner read the git tag via `git` and set it into manifest.json via a lib (maybe `dot-json`?)

**Comment by bfred-it** [comment]
Links fixed. Have a look.
