### ISSUE TITLE
Mozilla Addons

### ISSUE THREAD

**Issue by bfred-it** [npmhub/npmhub#20]
@zeke Do you mind if I publish it to AMO?

https://developer.mozilla.org/en-US/Add-ons/Distribution

**Comment by bfred-it** [comment]
What's License?

**Comment by zeke** [comment]
MIT ftw

**Comment by zeke** [comment]
:shipit:

**Comment by bfred-it** [comment]
I submitted it, it might take a month. I'll let you know 🙂

**Comment by zeke** [comment]
🦊

**Comment by silverwind** [comment]
Would it be possible deploy to AMO similar to how it's done for the Chrome store right now?

**Comment by bfred-it** [comment]
Eventually, probably. I had it planned for my other extension too https://github.com/GhostText/GhostText/issues/93

**Comment by silverwind** [comment]
Thanks! Part of the reason I was asking is that I was looking for a tool for it :)

**Comment by bfred-it** [comment]
I haven't tried it yet but it looks promising. It lacks a CLI, though

**Comment by bfred-it** [comment]
[Update on the missing cli](https://github.com/erikdesjardins/firefox-extension-deploy/issues/10): use mozilla's `web-ext sign`. It looks like it works, although not as smoothly as `chrome-webstore-upload` since [it throws an error even on success](https://i.imgur.com/W4QR63l.png) 😳

Also getting an API key is absurdly easy: https://addons.mozilla.org/en-US/developers/addon/api/key/ (although unfortunately you can only get one key at a time)

**Comment by zeke** [comment]
Nice!

Should we create a private maintainers repo for storing these creds?

**Comment by zeke** [comment]
Or does this stuff all just live on Travis?

**Comment by bfred-it** [comment]
They're already private on Travis, I think that's enough. I'll look into giving you access to npmhub on AMO like you did for Chrome Web Store

**Comment by bfred-it** [comment]
You can create your account here and I'll add your email: https://addons.mozilla.org/en-US/developers/addon/

**Comment by bfred-it** [comment]
Review ended, they asked [this change.](https://github.com/npmhub/npmhub/commit/125c7edfed36c62a4439a00ec054560e378c6b1c) It's been resubmitted 🚀

**Comment by zeke** [comment]
> create your account here and I'll add your email

✅ zeke@sikelianos.com

**Comment by zeke** [comment]
Just tried to install it but hit a few snags.

<img width="492" alt="screen shot 2017-02-24 at 8 52 19 pm" src="https://cloud.githubusercontent.com/assets/2289/23328329/61029208-fad3-11e6-9abc-6a5bc63c087e.png">

<img width="453" alt="screen shot 2017-02-24 at 8 52 31 pm" src="https://cloud.githubusercontent.com/assets/2289/23328337/8b7ba56a-fad3-11e6-9820-a920a4e7a571.png">

<img width="753" alt="screen shot 2017-02-24 at 8 55 06 pm" src="https://cloud.githubusercontent.com/assets/2289/23328341/8eeb2112-fad3-11e6-8931-4b44cfaf3666.png">

**Comment by bfred-it** [comment]
Right. We're waiting for the review

**Comment by zeke** [comment]
👍

**Comment by silverwind** [comment]
@zeke: Firefox release builds can't install unsigned extension anymore. You can use the [dev edition](https://www.mozilla.org/en-US/firefox/developer/) to do that.

**Comment by bfred-it** [comment]
<a href="https://addons.mozilla.org/en-US/firefox/addon/npm-hub/"><img src="https://i.imgur.com/7drHiqr.gif?noredirect" alt="it's happening"></a>
