### ISSUE TITLE
Merge with octolinker?

### ISSUE THREAD

**Issue by MWrathDev** [npmhub/npmhub#28]
https://github.com/octolinker/browser-extension/

**Comment by bfred-it** [comment]
Why merge? They don't have overlapping features

**Comment by zeke** [comment]
> They don't have overlapping features

True, but they serve similar purposes: Making the GitHub browsing experience better for javascript developers.

@MWrathDev what about opening a PR that adds a "See Also" section to the README which mentions OctoKit?

This could be added too: https://github.com/stefanbuck/awesome-browser-extensions-for-github

**Comment by bfred-it** [comment]
I still don't see the need to merge them. It's easier to handle multiple smaller packages than a big one. The only thing I'd suggest is to link each other in the readme

**Comment by bfred-it** [comment]
Ultimately, octolinker supports a variety of languages while npmhub only supports JS/npm.

Merging them would require **a lot** of effort just to reach their package manager support.
