### ISSUE TITLE
Allow for GitHub Enterprise support

### ISSUE THREAD

**Issue by bentruyman** [npmhub/npmhub#29]
It would be nice if there was an ability to add custom URLs for GitHub Enterprise instances.

**Comment by zeke** [comment]
That might be as simple as adding another pattern here...

https://github.com/npmhub/npmhub/blob/f242532bfee1c16439e8b189614063c20ceb4e80/extension/manifest.json#L29

**Comment by bfred-it** [comment]
I did this a while ago for a different extension: option page + domain field that adds a new permission to Chrome. I'll look for it's code next week

**Comment by bfred-it** [comment]
@bentruyman do you mind trying the [`ghe-support` branch](https://github.com/npmhub/npmhub/tree/ghe-support)?
