### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by MatthieuLemoine** [npmhub/npmhub#32]
Did you plan to support GitLab ? 

It could be nice to support both GitHub and GitLab as [octotree](https://github.com/buunguyen/octotree) does.

**Comment by zeke** [comment]
Totally open to the idea! Would you be interested in giving it a try, @MatthieuLemoine?

**Comment by MatthieuLemoine** [comment]
@zeke Sure ! I will look at it tomorrow.
