### ISSUE TITLE
package names are missing

### ISSUE THREAD

**Issue by zeke** [npmhub/npmhub#34]
cc @bfred-it 

<img width="1017" alt="screen shot 2017-02-21 at 2 49 34 pm" src="https://cloud.githubusercontent.com/assets/2289/23188834/0b11f5d6-f845-11e6-893b-8f96b5288aec.png">

**Comment by bfred-it** [comment]
Darnit. My bad. Will fix soon

**Comment by zeke** [comment]
Working for me. Thanks for fixing!

<img width="696" alt="screen shot 2017-02-21 at 8 42 01 pm" src="https://cloud.githubusercontent.com/assets/2289/23197598/3dc4d422-f876-11e6-88fe-497001ff3c01.png">

**Comment by bfred-it** [comment]
Good! Sorry about that! That's what happens with "this is a small change what could possibly go wrong let's not test it" 😅
