### ISSUE TITLE
Remove use of jquery

### ISSUE THREAD

**Issue by erikvold** [npmhub/npmhub#37]
This extension would be much smaller, faster, and easier to maintain without jquery imo.

**Comment by bfred-it** [comment]
I'd argue that without jQuery it would actually make it harder to maintain.

I thought about removing the dependency but that chaining currently makes the code quite lean. Plus jQuery is preloaded and by itself it's not a huge hog. 

PRs to remove it are welcome from me (HBU @zeke?), as long as the code doesn't grow too much.

**Comment by zeke** [comment]
I don't feel strongly about it. Open to a pull request.
