### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by erikvold** [npmhub/npmhub#38]
Using https://github.com/tmpvar/jsdom it's pretty easy to write some tests for web extensions.

**Comment by bfred-it** [comment]
Do you have examples of other extensions usin tests? I don't think jsdom provides `chrome.*` APIs and it'd be a pain to rewrite those.

**Comment by erikvold** [comment]
> I don't think jsdom provides chrome.* APIs and it'd be a pain to rewrite those.

Using https://github.com/acvetkov/sinon-chrome helps with that
