### ISSUE TITLE
Use browserify

### ISSUE THREAD

**Issue by erikvold** [npmhub/npmhub#43]
It'd be easier to test the extension (since we'll have modules that can be unit tested) and easier use modules from npm if the project used [browserify](http://browserify.org/).  This would also make #37 easier to do.

**Comment by erikvold** [comment]
nvm I just looked at how small this extension is and perhaps this would be overkill.

**Comment by erikvold** [comment]
I take it back, it only looks small but a lot is being done, using jquery to find a link for the `package.json`, fetching a html page for the `package.json` file, using jquery to parse the entire response page, then using jquery to output the view.

**Comment by bfred-it** [comment]
However you describe it, it's still 76 lines long with a single dependency. 

The only reason I'd split this into multiple modules (at this filesize) would be if it **considerably** helped testing it, otherwise we'd just be making one thing more complex to slightly simplify another.
