### ISSUE TITLE
HTML in descriptions is not escaped/sanitized

### ISSUE THREAD

**Issue by zeke** [npmhub/npmhub#49]
Example: https://github.com/hypermodules/sitedown

Notice how `<mark> tag plugin for markdown-it markdown parser` ends up injecting a `<mark>` element into the page!

![screen shot 2017-03-29 at 10 16 19 pm](https://cloud.githubusercontent.com/assets/2289/24488687/767b57a0-14cd-11e7-908b-a0e07679ba62.png)

**Comment by bfred-it** [comment]
Fixed in c7a40bf201c4d52de548062b4626b168b8176d82

**Comment by zeke** [comment]
Thanks!

**Comment by bfred-it** [comment]
Welcome back! :D
