### ISSUE TITLE
Display also module version

### ISSUE THREAD

**Issue by roccomuso** [npmhub/npmhub#56]
Couldn't be a useful improvement?

Better if configurable from the settings.

**Comment by bfred-it** [comment]
It used to be there but it was removed: https://github.com/npmhub/npmhub/pull/15

I'm thinking it can be added back, hidden, and you can show it again via userstyle

**Comment by zeke** [comment]
hidden is okay with me.

@roccomuso why do you think you want to know the versions?

**Comment by roccomuso** [comment]
Well a few days ago it would have been useful to me, so why not.

**Comment by zeke** [comment]
I'm just trying to understand you use case.

> it would have been useful to me

why?

> why not?

because it takes up space, adds to cognitive load, and probably is not useful information most of the time. In most cases you just want to know what the dependency is for, and possibly click through to learn more about it.

**Comment by roccomuso** [comment]
> why?

I was just comparing module dependencies across different repos.

> it takes up space, ...

I agree with you. That's why I said "better if configurable from settings".

**Comment by bfred-it** [comment]
Feel free to send a PR reinstating the version, keeping it hidden. Perhaps also mention how to enable it in the readme below the screenshot .
