### ISSUE TITLE
Repositories with no readme are producing an error

### ISSUE THREAD

**Issue by hkdobrev** [npmhub/npmhub#61]
E.g. https://github.com/pablopunk/whoami-api

When adding the box below the readme, the JavaScript is expecting the readme to be in the DOM. It should work around missing readme.

```
content.js:349
Uncaught (in promise) TypeError: Cannot read property 'tagName' of null
    at createBox (content.js:349)
    at init (content.js:295)
    at gitHubInjection (content.js:95)
    at content.js:377
    at content.js:379
```

**Comment by bfred-it** [comment]
Also: https://github.com/npmhub/npmhub/blob/master/README.md
