### ISSUE TITLE
npmhub stopped working

### ISSUE THREAD

**Issue by zeke** [npmhub/npmhub#66]
I just noticed this today. Something is up with the JSON response. Doesn't look like npmhub has changed recently. Any ideas, @bfred-it?

![screen shot 2017-08-09 at 1 09 00 pm](https://user-images.githubusercontent.com/2289/29141686-14f12308-7d04-11e7-8f2d-150aaaf4aa80.png)

<img width="678" alt="screen shot 2017-08-09 at 1 09 21 pm" src="https://user-images.githubusercontent.com/2289/29141695-17baf5f0-7d04-11e7-8803-b6065d3f5191.png">

**Comment by Justineo** [comment]
@zeke That's probably because GitHub updated their DOM structure lately. For more comprehensive and maintainable solution we might have to request data from GitHub API which returns file content in valid and predictable JSON responses.

**Comment by bfred-it** [comment]
Yeah we should just do that at some point, I'll open an issue to add a field for a personal token to support private repos. That's how most extensions handle them.

**Comment by bfred-it** [comment]
Fixed by #67
