### ISSUE TITLE
Use GitHub API with personal token 

### ISSUE THREAD

**Issue by fregante** [npmhub/npmhub#68]
- [ ] Add personal GitHub token field in options
- [ ] Make GitHub requests to GitHub's API (which is at `https://api.github.com` or `/api` on GHE, I think)

**Comment by fregante** [comment]
This is not necessary, it just complicates things and will require the user to enter a token.

**Comment by fharper** [comment]
It is necessary if you use more than one Chrome Extension that do not let you use a personal token. Most extension don't require you to add a token, but if you want to bypass the api rate limit, you can, so it's really not more complicated for the user, and solve issues for power users :)
