### ISSUE TITLE
GitHub's own dependency graph (thoughts)

### ISSUE THREAD

**Issue by bfred-it** [npmhub/npmhub#78]
<img width="766" alt="" src="https://user-images.githubusercontent.com/1402241/31483037-6dd58dec-aef0-11e7-9427-a6f1cdca71a7.png">

Link: https://github.com/npmhub/npmhub/network/dependencies

Should npmhub just fetch that view? Maybe not, npmhub's implementation might still be preferable because:

- works on non-root package.json
- UI highlights dev and peer deps
- shows descriptions
- works with non-github packages, [like buble here](https://github.com/bfred-it/npm-bundler/network/dependencies)

I think we should at least add a shortcut/button/link to the page, since it's 2 page-loads away from a repo's root (Insights > Dependency graph)

**Comment by olstenlarck** [comment]
I don't know what the benefit of the GitHub's one is.. probably works for other languages and package mangers? If so, then it would make sense to just fetch that, yea.

Otherwise I don't see any reason to use that github page, since i can just click the package.json :D

**Comment by bfred-it** [comment]
Given that Ruby is the only other supported language I'm less interested about that. But yeah, currently the only advantage is that it lets you see sub-dependencies. The huge problem at the moment is that it mixes dev and non-dev dependencies, so it's kind of useless. Closing this altogether for now.

**Comment by bfred-it** [comment]
It does have some interesting ideas though, like showing the username, avatar and [version](https://github.com/npmhub/npmhub/issues/56)

<img width="736" alt="screen shot 2017-10-26 at 16 18 13" src="https://user-images.githubusercontent.com/1402241/32042256-8933752e-b9fc-11e7-9eb4-a7acecb4b8f1.png">
