### ISSUE TITLE
Support custom NPM registry

### ISSUE THREAD

**Issue by krohrsb** [npmhub/npmhub#86]
I'd like the option of specifying an alternate NPM registry to do the lookups from if possible. I'm in an enterprise environment. Authorizing my enterprise github works well, however we also have an enterprise NPM registry :) So would like to support that as well.

**Comment by zeke** [comment]
@krohrsb sounds good to me. Would you be willing to take a shot at implementing this?

**Comment by bfred-it** [comment]
Ideal solution here, if anyone builds it: https://github.com/sindresorhus/module-requests/issues/114
