### ISSUE TITLE
Githack links

### ISSUE THREAD

**Issue by brettz9** [npmhub/npmhub#89]
Would it be in scope enough for you to consider linking individual pages (at least `.html`/`.htm` ones) to https://raw.githack.com/ ?

**Comment by bfred-it** [comment]
Which pages? Where would you put this link?

**Comment by brettz9** [comment]
Like if I've navigated to https://github.com/SVG-Edit/svgedit/blob/master/editor/svg-editor.html , there could be a link next to "Raw", "Blame", "History"

**Comment by bfred-it** [comment]
Completely unrelated to **npm**hub, sorry

**Comment by bfred-it** [comment]
But: https://github.com/sindresorhus/refined-github/issues/1595

**Comment by brettz9** [comment]
Thanks for pointing me to the repo--that does look like a better place to try, thanks!
