### ISSUE TITLE
CORB are blocking request to NPM registry

### ISSUE THREAD

**Issue by jukben** [npmhub/npmhub#92]
~~CORS~~ CORB are blocking request to NPM registry. Not sure what we can do about it. Any idea?

**Comment by bfred-it** [comment]
It's CORB: https://www.chromestatus.com/feature/5629709824032768

Sigh. They changed the behavior in Chrome 73: https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

> any content scripts that do need to make cross-origin requests can do so via an extension background page, which can relay the data to the content script.  We have a migration plan below to help affected extension developers make the transition to the new model.

That page contains a migration code, if anyone wants to submit a PR:

> Old content script, making a cross-origin fetch:
> ```js
> var itemId = 12345;
> var url = "https://another-site.com/price-query?itemId=" +
>          encodeURIComponent(request.itemId);
> fetch(url)
>   .then(response => response.text())
>   .then(text => parsePrice(text))
>   .then(price => ...)
>   .catch(error => ...)
> ```
>
> New content script, asking its background page to fetch the data instead:
> ```js
> chrome.runtime.sendMessage(
>     {contentScriptQuery: "queryPrice", itemId: 12345},
>     price => ...);
> ```
> 
> New extension background page, fetching from a known URL and relaying data:
> ```js
> chrome.runtime.onMessage.addListener(
>   function(request, sender, sendResponse) {
>     if (request.contentScriptQuery == "queryPrice") {
>       var url = "https://another-site.com/price-query?itemId=" +
>               encodeURIComponent(request.itemId);
>       fetch(url)
>           .then(response => response.text())
>           .then(text => parsePrice(text))
>           .then(price => sendResponse(price))
>           .catch(error => ...)
>       return true;  // Will respond asynchronously.
>     }
>   });
> ```

However it needs to user `await` instead of `.then`

**Comment by bfred-it** [comment]
Also npm won't add CORS, if anyone was hoping that: https://github.com/npm/npm-registry-couchapp/issues/108

**Comment by jukben** [comment]
Hey, thanks for clarification. However, before I wrote this issue I had an assumption that it might be something like that so I've just quickly hacked the request in background page one of my extensions I'm working on. The same resoult with the same issue 

```
Access to fetch at 'https://registry.npmjs.org/alfred-emoji' from origin 'chrome-extension://aleo...' has been blocked by CORS policy...
```

So I'm not sure if it's really this case otherwise I'd be willing to do the PR.

**Comment by bfred-it** [comment]
It seems to work in npmhub's background page (Chrome 73), it could be that your extension doesn't have permission to npmjs.org

<img width="831" alt="Screenshot 2019-03-16 at 18 39 35" src="https://user-images.githubusercontent.com/1402241/54474048-ecc20a80-481a-11e9-8f3e-5d16adf55f47.png">

**Comment by jukben** [comment]
Ah! You are right 🤦‍♂️ that's the issue, sorry for confusion. I can work on that then 👍 Shell I go for it?

**Comment by bfred-it** [comment]
No worries, I just copied and pasted the notice from the console 😄
