### ISSUE TITLE
no deps, broken image

### ISSUE THREAD

**Issue by toklok** [npmhub/npmhub#95]
![image](https://user-images.githubusercontent.com/7063845/57484561-5688ee80-7277-11e9-8f19-c5908a6edb61.png)

broken image if no deps.

**Comment by bfred-it** [comment]
What browser/OS are you on?

**Comment by toklok** [comment]
Chrome 76 on Linux.

**Comment by bfred-it** [comment]
Anything more specific than Linux?

Do other emojis work on GitHub? Can you send me the markup of this emoji?  🇮🇹

**Comment by toklok** [comment]
https://assets-cdn.github.com/images/icons/emoji/unicode/1f389.png

![image](https://user-images.githubusercontent.com/7063845/57952206-71341680-78ba-11e9-82ac-9f6ff54e49c3.png)

**Comment by bfred-it** [comment]
Thanks! I didn't remember we include the URL as well. I updated it
