### ISSUE TITLE
Add link to UNPKG

### ISSUE THREAD

**Issue by fregante** [npmhub/npmhub#97]
Inspecting the content of the actual `npm` package would be pretty useful. Often it doesn't match what's on the repo. Example:

- https://github.com/fregante/webext-storage-cache (TypeScript source)
- https://www.unpkg.com/browse/webext-storage-cache@latest/ (ESM module)

**Comment by fregante** [comment]
Added and tweeted about it https://twitter.com/fregante/status/1230076269804412928

<img width="582" alt="" src="https://user-images.githubusercontent.com/1402241/74825875-9a9c3a00-5345-11ea-95d0-1835be2ee388.png">

**Comment by zeke** [comment]
Nice!
