### ISSUE TITLE
Chrome Store rejected new versions (privacy info)

### ISSUE THREAD

**Issue by fregante** [npmhub/npmhub#98]
> Publish condition not met: To publish your item, you must provide mandatory privacy information. This can be done in the new Developer Dashboard: https://chrome.google.com/webstore/devconsole.

Related Refined GitHub issue, probably parts of it can be copied: https://github.com/sindresorhus/refined-github/issues/2685

@zeke can you look into it?

**Comment by zeke** [comment]
👀

**Comment by zeke** [comment]
Hoping to get to this today. 🤞

**Comment by fregante** [comment]
I looked into it and it already has some info entered. I’m not sure what the issue is. Alternatively you can try manually uploading a new version and follow the instructions

**Comment by fregante** [comment]
The extension was not currently in a "reviewing" state, so I manually uploaded version 2020.3.28 and now we'll have to wait for it

<img width="828" alt="pending review" src="https://user-images.githubusercontent.com/1402241/77931171-1cb84080-72ac-11ea-8f1e-bd320b519c60.png">

**Comment by zeke** [comment]
Okay thanks. Anything needed on my part right now?

**Comment by fregante** [comment]
No, we'll just have to wait a week or more

**Comment by fregante** [comment]
> No, we'll just have to wait a week or more

Kidding! v2020.3.28 is already on the store! https://chrome.google.com/webstore/detail/npmhub/kbbbjimdjbjclaebffknlabpogocablj

**Comment by zeke** [comment]
Nice! 🙌
